services:
  dind:
    image: docker:dind
    privileged: true
    restart: always
    environment:
      TZ: America/Chicago
      DOCKER_TLS_CERTDIR: /certs
    healthcheck:
      test: ["CMD-SHELL", "docker version > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - dind-certs-ca:/certs/ca
      - dind-certs-client:/certs/client
      - dind-var-lib-docker:/var/lib/docker
      - runner-externals:/home/runner/externals
      - runner-work:/home/runner/_work

  runner:
    image: ghcr.io/djarbz/gha-runner:latest
    restart: always
    depends_on:
      dind: { condition: service_healthy }
    volumes:
      - dind-certs-client:/certs/client:ro
      - dind-var-lib-docker:/var/lib/docker
      - runner-externals:/home/runner/externals
      - runner-work:/home/runner/_work
    environment:
      TZ: America/Chicago
      DOCKER_HOST: tcp://dind:2376/
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS: 1
      # These variables are loaded from the global .env file
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REPOSITORY: ${GITHUB_REPOSITORY}
      # DEBUG: true
    deploy:
      mode: replicated
      replicas: 1 # Specifies the desired number of replicas

volumes:
  dind-certs-client:
  dind-certs-ca:
  dind-var-lib-docker:
  runner-externals:
  runner-work:
