services:
  runner:
    image: ghcr.io/djarbz/gha-runner:latest
    restart: always
    group_add:
      - "989"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-externals:/home/runner/externals
      - runner-work:/home/runner/_work
    environment:
      TZ: America/Chicago
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REPOSITORY: ${GITHUB_REPOSITORY}
      DEBUG: true
    deploy:
      mode: replicated
      replicas: ${REPLICAS}

volumes:
  runner-externals:
  runner-work:
