services:
  runner:
    image: ghcr.io/djarbz/gha-runner:latest
    restart: always
    privileged: true
    extra_hosts:
      - "registry.local:host-gateway"
    tmpfs:
      - /var/run
    volumes:
      - runner-externals:/home/runner/externals
      - runner-work:/home/runner/_work
      - runner-var-lib-docker:/var/lib/docker
    environment:
      TZ: ${TZ:-America/Chicago}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REPOSITORY: ${GITHUB_REPOSITORY}
      DEBUG: true
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}

volumes:
  runner-externals:
  runner-work:
  runner-var-lib-docker:
