services:
  dind:
    image: docker:dind
    privileged: true
    restart: always
    environment:
      TZ: America/Chicago
      DOCKER_TLS_CERTDIR: /certs
    healthcheck:
      test: ["CMD-SHELL", "docker version > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - dind-certs-ca:/certs/ca
      - dind-certs-client:/certs/client
      - dind-var-lib-docker:/var/lib/docker
      - runner-externals:/home/runner/externals
      - runner-work:/home/runner/_work

  dind-proxy:
    image: alpine:latest
    restart: always
    network_mode: "service:dind"
    depends_on:
      dind: { condition: service_healthy }
    # Listens on DinD's port 5000, and forwards out to the Debian Host VM's global registry
    command: >
      sh -c "apk add --no-cache socat &&
      HOST_IP=$$(ip route | awk '/default/ {print $$3}') &&
      socat TCP-LISTEN:5000,fork TCP:$${HOST_IP}:5000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:5000/v2/"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  runner:
    image: ghcr.io/djarbz/gha-runner:latest
    restart: always
    depends_on:
      dind: { condition: service_healthy }
    volumes:
      - dind-certs-client:/certs/client:ro
      - runner-externals:/home/runner/externals
      - runner-work:/home/runner/_work
    environment:
      TZ: America/Chicago
      DOCKER_HOST: tcp://dind:2376/
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS: 1
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REPOSITORY: ${GITHUB_REPOSITORY}
      DEBUG: true
    deploy:
      mode: replicated
      replicas: ${REPLICAS}

volumes:
  dind-certs-client:
  dind-certs-ca:
  dind-var-lib-docker:
  runner-externals:
  runner-work:
